---
- include:              '../tasks/install_packages.yml'
- include:              '../tasks/git_repos.yml'
- include:              '../tasks/commands.yml'
- include:              '../tasks/symlinks.yml'
