---
- include_tasks:        '../tasks/install_packages.yml'
- include_tasks:        '../tasks/git_repos.yml'
- include_tasks:        '../tasks/commands.yml'
- include_tasks:        '../tasks/symlinks.yml'
